name: nrfutil_example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  universal_html: ^2.2.3
  cupertino_icons: ^1.0.5

dev_dependencies:
  nrfutil:
    path: ../
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
nrfutil:
  debug: true
  comment: "test comment"
  softdevice_type: "s132NRF52d611"
  export_path: "assets"
  hardware_version: 0xFFFFFFFF
  keyfile:
    generate: false
    private_key: "assets/key.pem"
    public_key: "assets/pbkey.pem"
  bootloader:
    version: 0xFFFFFFFF
    path: "assets/firmwares/bar.hex"
  application:
    version: 0xFFFFFFFF
    path: "assets/firmwares/bar.hex"
  softdevice:
    version: 0xFFFFFFFF
    path: "assets/firmwares/foo.hex"
  settings: #this needs keys, softdevice, and application to work
    generate: true
    bl_sett_version: 1 #1,or œ2
    no_backup: true
    #import_settings: "assets/firmwares/bl_settings_v1_nrf52.hex"
    arch: "NRF51" #'NRF51','NRF52','NRF52QFAB','NRF52810',or 'NRF52840'
    #custom_boot_sett_addr: 0x0006F000 #can be null
    #backup_address: 0x0006F000 #can be null
    sd_val_type:  'p256' #null,'p256','crc','sha256'
    app_val_type: 'p256' #null,'p256','crc','sha256'


flutter:
  uses-material-design: true
  assets:
    - assets/key.pem
    - assets/firmwares/
