name: nrfutil
description: A Flutter plugin to create nRF DFU packages with signing for DFU updates on nRF51 and nRF52 devices.
version: 0.0.4
repository: https://github.com/Knightro63/flutter_nrfutil

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.7
  protobuf: ^3.0.0
  basic_utils: ^5.6.1
  crypto: ^3.0.3
  yaml: ^3.1.2
  args: ^2.4.2
  logger: ^2.0.2+1
  checked_yaml: ^2.0.3
  json_annotation: ^4.8.1
  path: ^1.8.3
  bisection: ^0.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

false_secrets:
 - /lib/signing.dart
 - /example/assets/key.pem
 - /example/assets/pbkey.pem
 - /example/assets/pbkey.c
