name: nrfutil
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/Knightro63/flutter_nrfutil

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.1
  protobuf: ^2.1.0
  basic_utils: ^4.5.2
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

false_secrets:
 - /lib/signing.dart
 - /example/nrfutil_example/assets/key.pem
